CREATE DATABASE M_MeuPonto

USE M_MeuPonto

CREATE TABLE Usuarios(
	IdUsuario INT IDENTITY NOT NULL PRIMARY KEY
	,Ni VARCHAR(255) NOT NULL
	,Nome VARCHAR(255)  NOT NULL
	,CPF CHAR(11)  NOT NULL UNIQUE
	,Email VARCHAR(255) NOT NULL UNIQUE
	,Senha VARCHAR(255) NOT NULL 
	,Tipo VARCHAR(255) NOT NULL 
)

CREATE TABLE Pontos(
	IdPonto INT IDENTITY NOT NULL PRIMARY KEY
	,IdUsuario INT FOREIGN KEY REFERENCES Usuarios(IdUsuario)
	,DataHorario DateTime NOT NULL
	,Tipo VARCHAR(255) NOT NULL 
)

